### ISSUE TITLE
responsive slider

### ISSUE THREAD

**Issue by cmnstmntmn** [ArthurClemens/mithril-slider#1]
i figured to make it responssive by changing width values from `px` to `vw`

``` js
const posPx = (i - 1) * 100 + 'vw';
```

and few other style declarations, got modified this way.

the problem is with **.content** wraper's width that doesn't get updated (based on it's content)

anyway i managed to fix this, the following way:

i call `m.redraw()` in the view, at window resize event

``` js
window.addEventListener("resize", function(e) {
   m.redraw() //notify view
})
```

is this ok, or there's a more elegant way to do it ?

**Comment by ArthurClemens** [comment]
Good suggestion. I will look into it in a couple of days.

**Comment by ArthurClemens** [comment]
An alternative approach is to use `calc()`

**Comment by futurist** [comment]
You can use this lib https://github.com/cssobj/cssobj instead of `calc()` or `vw` for better combatibility.

Or, instead of `j2c`.
