### ISSUE TITLE
Calling a Promise?

### ISSUE THREAD

**Issue by TimMensch** [ArthurClemens/mithril-slider#4]
I'm getting an immediate crash when I try to use a Promise for pageData:

```
   pageData: ()=>Promise.resolve([1,2,3,4]),
```

It starts out with a `list.then()`, which is fine, but later accesses the Promise illegally with list(). The only way to get data from a promise is with promise.then(). Not sure how that can ever work (except that presumably m.request() supports a call?).

**Comment by ArthurClemens** [comment]
`list` is a bit too dependent on the way `m.request` resolves. Working on an update.

**Comment by ArthurClemens** [comment]
Fixed in 0.4.0. Code example https://github.com/ArthurClemens/mithril-slider/blob/master/packages/examples/src/controls/index.js#L44
