### ISSUE TITLE
Many window-level events created as slider is shown and hidden

### ISSUE THREAD

**Issue by JohnAnthony** [ArthurClemens/mithril-slider#6]
I'm getting double scroll events in Chrome - it looks like an extra set of pointercancel, pointermove and pointerup events are being attached. It doesn't happen every time, and I suspect a timing issue based upon how long the slider takes to render. If the slider is switched out and in again on a redraw of the view, more handlers are added.

![double](https://user-images.githubusercontent.com/436859/27337795-5e2cc690-55cb-11e7-8449-ac894907c78c.png)

Here's as stripped-down as I can get the issue. Because it's much simpler, the bug manifests less often, but in more complex code it happens every time.

https://gist.github.com/JohnAnthony/32dc028af0098a1d64adc388b3e3dc25

**Comment by ArthurClemens** [comment]
I can't reproduce it. Does it still happen?

**Comment by JohnAnthony** [comment]
It's been a long time since I looked at this. I'll have a shot at reproducing it when I get time and get back to you.
